# Generated by Django 3.1.4 on 2020-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.IntegerField(max_length=15),
        ),
    ]
