# Generated by Django 3.1.4 on 2020-12-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20201225_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.IntegerField()),
                ('coupon', models.CharField(max_length=30)),
            ],
        ),
    ]
