# Generated by Django 3.1.4 on 2020-12-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_subscribe_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe_customer',
            name='coupon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
